### ISSUE TITLE
Error with simultaneous incoming file transfers

### ISSUE THREAD

**Issue by dwmw2** [tieto/sipe#5] opened 2015-03-09 16:24 UTC
If someone sends me two files in quick succession and I accept them both, neither works. The sender reports that both have failed, while my end still shows them as 'Waiting for transfer to begin'.

If I then try to cancel one by hitting the 'Stop' button, pidgin crashes:

```
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106             movdqu  (%rax), %xmm12
#0  0x00000030da28ac8a in strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00000037bfc67c43 in g_strdup (str=0x1 <error: Cannot access memory at address 0x1>) at gstrfuncs.c:355
#2  0x00007fffe35fcfe4 in sip_transport_request_timeout (sipe_private=0x1466cc0, method=method@entry=0x7fffe3633551 "INFO", url=0x20 <erro
r: Cannot access memory at address 0x20>, to=0x20 <error: Cannot access memory at address 0x20>, addheaders=addheaders@entry=0x7fffe3645f2
8 "Content-Type: application/ms-filetransfer+xml\r\n", body=body@entry=0x1464660 "<request xmlns=\"http://schemas.microsoft.com/rtc/2009/0
5/filetransfer\" requestId=\"28\"/><cancelTransfer><transferId>27</transferId><fileInfo><id>{192D68DD-D9B7-47E2-86DA-73745C1E30E5}</id><na
me>DSCN046"..., dialog=0x1c0b1b0, callback=0x7fffe36286c0 <cancel_transfer_cb>, timeout=0, timeout_callback=0x0) at sip-transport.c:723
#3  0x00007fffe35fe645 in sip_transport_request (sipe_private=<optimized out>, method=method@entry=0x7fffe3633551 "INFO", url=<optimized o
ut>, to=<optimized out>, addheaders=addheaders@entry=0x7fffe3645f28 "Content-Type: application/ms-filetransfer+xml\r\n", body=body@entry=0
x1464660 "<request xmlns=\"http://schemas.microsoft.com/rtc/2009/05/filetransfer\" requestId=\"28\"/><cancelTransfer><transferId>27</trans
ferId><fileInfo><id>{192D68DD-D9B7-47E2-86DA-73745C1E30E5}</id><name>DSCN046"..., dialog=0x1c0b1b0, callback=0x7fffe36286c0 <cancel_transf
er_cb>) at sip-transport.c:851
#4  0x00007fffe35fe6cf in sip_transport_info (sipe_private=<optimized out>, addheaders=addheaders@entry=0x7fffe3645f28 "Content-Type: appl
ication/ms-filetransfer+xml\r\n", body=body@entry=0x1464660 "<request xmlns=\"http://schemas.microsoft.com/rtc/2009/05/filetransfer\" requ
estId=\"28\"/><cancelTransfer><transferId>27</transferId><fileInfo><id>{192D68DD-D9B7-47E2-86DA-73745C1E30E5}</id><name>DSCN046"..., dialo
g=<optimized out>, callback=callback@entry=0x7fffe36286c0 <cancel_transfer_cb>) at sip-transport.c:895
#5  0x00007fffe362879e in ft_lync_incoming_cancelled (ft_private=0x156c7f0, ft_private=0x156c7f0, callback=0x7fffe36286c0 <cancel_transfer
_cb>, body=0x1464660 "<request xmlns=\"http://schemas.microsoft.com/rtc/2009/05/filetransfer\" requestId=\"28\"/><cancelTransfer><transfer
Id>27</transferId><fileInfo><id>{192D68DD-D9B7-47E2-86DA-73745C1E30E5}</id><name>DSCN046"...) at sipe-ft-lync.c:90
#6  0x00007fffe362879e in ft_lync_incoming_cancelled (ft=0x156c7f0, local=<optimized out>) at sipe-ft-lync.c:349
#7  0x00007fffe362d872 in ft_cancelled (xfer=0x162e960 [PurpleXfer]) at purple-ft.c:220
#8  0x00007ffff7a0811d in purple_xfer_cancel_local (xfer=0x162e960 [PurpleXfer]) at xfer.c:1748
#9  0x00000037c000fe84 in _g_closure_invoke_va (closure=closure@entry=0x1e10e00, return_value=return_value@entry=0x0, instance=instance@en

```

**Comment by xhaakon** [comment] 2015-09-17 18:40
There were some changes done lately in order to improve parallel media and file transfers. Could you please check whether this problem is still reproducible for you?

**Comment by xhaakon** [comment] 2016-05-06 09:18
Closing since it's been checked this is working in the latest PPA version.

**Closed as completed by xhaakon** 2016-05-06 09:18 UTC
