### ISSUE TITLE
Sharing a screen from SIPE to MS SFB only displays a black screen

### ISSUE THREAD

**Issue by joakim-tjernlund** [tieto/sipe#142] opened 2017-02-15 14:56 UTC
I think this worked at one point but recently the MS SFB user only sees a black screen.
Using recent git for both sipe and freedrp

**Comment by xhaakon** [comment] 2017-02-15 16:34
This sounds like the regression in FreeRDP I know about. Here's how to fix it:

* Please make sure FreeRDP you're using includes [this commit](https://github.com/FreeRDP/FreeRDP/pull/3669/commits/463cb4159619f74c3ee626d0d71a2859c5a705c1) (if your checkout is less than a month old, you should already have it).
* Apply [this patch](https://github.com/xhaakon/sipe/commit/930d9bbb4d8b2dc55750ea13f921eb38617deace) on your Sipe.

The latter change isn't in sipe-collab, which still uses older (working) FreeRDP snapshot and also the patch isn't compilable with that version.

**Comment by joakim-tjernlund** [comment] 2017-02-15 17:06
YES, the last patch to pidgin-spie did it! (already had the freerdp patch)

Also, recently I tracked down a SEGV in Remmina when sharing screen to a smaller screen.
Update to latest freerdp to avoid that.

**Comment by xhaakon** [comment] 2017-02-15 17:14
> Also, recently I tracked down a SEGV in Remmina when sharing screen to a smaller screen.
Update to latest freerdp to avoid that.

Good to know. Did you compile the latest Remmina against the latest FreeRDP? I remember it wasn't possible the last time I tried about a month ago.

The issue is solved, so closing.

**Closed as completed by xhaakon** 2017-02-15 17:14 UTC

**Comment by joakim-tjernlund** [comment] 2017-02-15 17:16
Yes, it is fixed now. I just rebuild Remmina git against freerdp git to be sure :)

**Comment by joakim-tjernlund** [comment] 2017-02-15 17:21
Oh, any chance to add the fix to lanchpad branch ? 
Also resync launchpad against upstream pidgin-sipe?
BTW, I still build against pidgin 2

**Comment by xhaakon** [comment] 2017-02-15 19:18
> Also resync launchpad against upstream pidgin-sipe?

I'm rather reluctant to perform bigger changes on sipe-collab nowadays. The packages installable from the PPA are in a quite stable state and updating them would IMO add only little value to the users to justify the risk of breaking some stuff.

Because I can no longer use my working hours for maintaining Sipe, I'd rather invest the time I have left into upstream work and thus getting the changes directly into distributions (hence RDP viewer in 1.22.0), with the ultimate prospect of one day shutting down the PPA and the associated GitHub repos. It was always meant as a temporary area for new features developed in association with Ericsson, but has unfortunately grown bigger than originally expected.

> Oh, any chance to add the fix to lanchpad branch ?

This can't be done without FreeRDP update as the patch code doesn't compile against FreeRDP in sipe-collab.

> BTW, I still build against pidgin 2

That's completely fine, all important features are backported and should work. Pidgin 3 has its own deal of problems and it appears the upstream development has stalled in past months so I don't expect a stable release anytime soon. Actually, I'm considering reverting my development setup back to Pidgin 2 myself too.

**Comment by joakim-tjernlund** [comment] 2017-03-02 01:39
> Because I can no longer use my working hours for maintaining Sipe, I'd rather invest the time I have left into upstream work and thus getting the changes directly into distributions (hence RDP viewer in 1.22.0), with the ultimate prospect of one day shutting down the PPA and the associated GitHub repos. It was always meant as a temporary area for new features developed in association with Ericsson, but has unfortunately grown bigger than originally expected.

Any chance this will happen soon? There are a few bug fixes more upstarem so I would love to switch sooner than later :)

**Comment by xhaakon** [comment] 2017-03-02 10:09
You may want to try my personal branch here then: https://github.com/xhaakon/sipe/commits/lp-rebase

It contains the patches left in sipe-collab (i.e. mostly the RDP server) on top of the current upstream, which I guess is what you want.

When rebasing the Collab code, I had to do some non-trivial updates to make it apply cleanly onto mainline mob branch and the result isn't very well tested yet, but the basic RDP presenter stuff should work.

**Comment by joakim-tjernlund** [comment] 2017-03-02 19:04
I have noted in pidgin 2 that in "Input and Output Settings", Device is always "Default".
I cannot change it. Have you seen that too?

**Comment by xhaakon** [comment] 2017-03-03 07:15
> In Pidgin 2 that in "Input and Output Settings", Device is always "Default".

Yes, media device detection in Pidgin 2 isn't available when Pidgin is built with GStreamer 1.0. I have re-implemented it into Pidgin 3, but the feature is not backported to 2.x.

**Comment by joakim-tjernlund** [comment] 2017-03-03 12:35
Any way you can point me to that commit(or backport it) in Pidgin3?

**Comment by xhaakon** [comment] 2017-03-03 13:10
Sure, see this pull request on Bitbucket: https://bitbucket.org/pidgin/main/pull-requests/86/gstreamer-10-media-device-management

**Comment by joakim-tjernlund** [comment] 2017-03-04 12:42
Ouch, that was quite a big change. Too much for me sort out for to get in into pidgin.
Is there some minimal diff that can be applied to pidgin2?

**Comment by xhaakon** [comment] 2017-03-06 06:42
>  Is there some minimal diff that can be applied to pidgin2?

I'm afraid the PR is as minimal as it can get...
