### ISSUE TITLE
pidgin screen sharing and video stopped working after remmina update

### ISSUE THREAD

**Issue by bergkatten** [tieto/sipe#183] opened 2018-04-23 07:00 UTC
It looks like the binary pigdin in the package pidgin-3.0.0~collab-1+201706131018~ubuntu16.04.1needs to be re-linked/compiled with the libs in the new remmina. 

Audio works but screen sharing and video is broken on Ubuntu 16.04.4.

**Comment by Daisuke-sama** [comment] 2018-08-07 14:15
I have the same issue. It shows me that `libfreerdp does not support H264`. Please, help asap.

**Comment by xhaakon** [comment] 2018-08-07 19:05
@Daisuke-sama Which distro are you on and which packages do you have installed (see mine below)? I've just tried 16.04 with PPA Sipe and screen sharing seems to work fine. Couldn't check video as I don't have a camera at the moment.

```
$ dpkg --list | grep -e sipe -e pidgin -e farstream -e remmina -e nice -e freerdp -e winpr
ii  gstreamer1.0-nice:amd64                     0.1.15~sipe-0+201802281442~ubuntu16.04.1                            amd64        ICE library (GStreamer plugin)
ii  libfarstream-0.2-5:amd64                    0.2.8+sipe+collab-1+201802080603~ubuntu16.04.1                      amd64        Audio/Video communications framework: core library
ii  libfreerdp-client2-2:amd64                  2.0.0~git20170725.1.1648deb+dfsg1+sipe-1~201803191823~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-server2-2:amd64                  2.0.0~git20170725.1.1648deb+dfsg1+sipe-1~201803191823~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow-subsystem2-2:amd64        2.0.0~git20170725.1.1648deb+dfsg1+sipe-1~201803191823~ubuntu16.04.1 amd64        FreeRDP Remote Desktop Protocol shadow subsystem libraries
ii  libfreerdp-shadow2-2:amd64                  2.0.0~git20170725.1.1648deb+dfsg1+sipe-1~201803191823~ubuntu16.04.1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp2-2:amd64                         2.0.0~git20170725.1.1648deb+dfsg1+sipe-1~201803191823~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libnice10:amd64                             0.1.15~sipe-0+201802281442~ubuntu16.04.1                            amd64        ICE library (shared library)
ii  libwinpr-tools2-2:amd64                     2.0.0~git20170725.1.1648deb+dfsg1+sipe-1~201803191823~ubuntu16.04.1 amd64        Windows Portable Runtime Tools library
ii  libwinpr2-2:amd64                           2.0.0~git20170725.1.1648deb+dfsg1+sipe-1~201803191823~ubuntu16.04.1 amd64        Windows Portable Runtime library
ii  pidgin                                      1:3.0.0~collab-1+201706131018~ubuntu16.04.1                         amd64        graphical multi-protocol instant messaging client
ii  pidgin-data                                 1:3.0.0~collab-1+201706131018~ubuntu16.04.1                         all          multi-protocol instant messaging client - data files
ii  pidgin-sipe                                 1.23.2+sipe-0+201807220102~ubuntu16.04.1                            amd64        Pidgin plugin for Skype for Business and Microsoft Lync
ii  remmina                                     1.2.0-rcgit.27+dfsg-3+sipe~201803191953~ubuntu16.04.1               amd64        GTK+ Remote Desktop Client
ii  remmina-common                              1.2.0-rcgit.27+dfsg-3+sipe~201803191953~ubuntu16.04.1               all          Common files for Remmina
ii  remmina-plugin-rdp:amd64                    1.2.0-rcgit.27+dfsg-3+sipe~201803191953~ubuntu16.04.1               amd64        RDP plugin for Remmina
ii  remmina-plugin-secret:amd64                 1.2.0-rcgit.27+dfsg-3+sipe~201803191953~ubuntu16.04.1               amd64        Secret plugin for Remmina
ii  remmina-plugin-vnc:amd64                    1.2.0-rcgit.27+dfsg-3+sipe~201803191953~ubuntu16.04.1               amd64        VNC plugin for Remmina
```

**Comment by Daisuke-sama** [comment] 2018-08-08 07:56
@xhaakon thanks for your input
Mine is below. BTW I am using Ubuntu 18.04. Is that a problem?

```
$ dpkg --list | grep -e sipe -e pidgin -e farstream -e remmina -e nice -e freerdp -e winpr
ii  freerdp2-x11                               2.0.0~git20170725.1.1648deb+dfsg1-7        amd64        RDP client for Windows Terminal Services (X11 client)
ii  gstreamer1.0-nice:amd64                    0.1.14-1                                   amd64        ICE library (GStreamer plugin)
ii  libfarstream-0.2-5:amd64                   0.2.8-4.1~build1                           amd64        Audio/Video communications framework: core library
ii  libfreerdp-client2-2:amd64                 2.0.0~git20170725.1.1648deb+dfsg1-7        amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp2-2:amd64                        2.0.0~git20170725.1.1648deb+dfsg1-7        amd64        Free Remote Desktop Protocol library (core library)
ii  libnice10:amd64                            0.1.14-1                                   amd64        ICE library (shared library)
ii  libwinpr2-2:amd64                          2.0.0~git20170725.1.1648deb+dfsg1-7        amd64        Windows Portable Runtime library
ii  pidgin                                     1:2.12.0-1ubuntu4                          amd64        graphical multi-protocol instant messaging client
ii  pidgin-data                                1:2.12.0-1ubuntu4                          all          multi-protocol instant messaging client - data files
ii  pidgin-libnotify                           0.14-9ubuntu2                              amd64        display notification bubbles in pidgin
ii  pidgin-sipe                                1.23.2-1                                   amd64        Pidgin plugin for Skype for Business and Microsoft Lync
ii  remmina                                    1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        GTK+ Remote Desktop Client
ii  remmina-common                             1.2.0-rcgit.29+dfsg-1ubuntu1               all          Common files for Remmina
ii  remmina-plugin-rdp:amd64                   1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        RDP plugin for Remmina
ii  remmina-plugin-secret:amd64                1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        Secret plugin for Remmina
ii  remmina-plugin-vnc:amd64                   1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        VNC plugin for Remmina
```

**Comment by xhaakon** [comment] 2018-08-08 08:11
@Daisuke-sama Ubuntu 18.04 is not a problem.

Oh, I see you're using `pidgin-sipe` directly from Ubuntu repository. I'm aware that pidgin-sipe                                1.23.2 and remmina 1.2.0-rcgit.29 don't work together. This will be fixed in the next Sipe release, but you can still install it now:

```
sudo apt-add-repository ppa:sipe-collab
sudo apt-get update
sudo apt-get upgrade
```

This will update `pidgin-sipe`, `freerdp2` and `libnice` packages.

**Comment by Daisuke-sama** [comment] 2018-08-08 10:34
@xhaakon I've done updating. But the same error is still shown to me. Do I need to uninstall previous packages and reboot?
Thanks

**Comment by xhaakon** [comment] 2018-08-08 11:43
> Do I need to uninstall previous packages and reboot?

None of that should be necessary, but don't forget to restart Pidgin and also Remmina tends to stay running in the background so kill all the remaining processes:

```
kill `pgrep remmina`
```

I've just checked 18.04 with PPA Sipe too and for me screen sharing works:

```
$ dpkg --list | grep -e sipe -e pidgin -e farstream -e remmina -e nice -e freerdp -e winpr
ii  gstreamer1.0-nice:amd64                    0.1.15~sipe-0+201807072216~ubuntu18.04.1   amd64        ICE library (GStreamer plugin)
ii  libfarstream-0.2-5:amd64                   0.2.8-4.1~build1                           amd64        Audio/Video communications framework: core library
ii  libfreerdp-client2-2:amd64                 2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-server2-2:amd64                 2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow-subsystem2-2:amd64       2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        FreeRDP Remote Desktop Protocol shadow subsystem libraries
ii  libfreerdp-shadow2-2:amd64                 2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp2-2:amd64                        2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Free Remote Desktop Protocol library (core library)
ii  libnice10:amd64                            0.1.15~sipe-0+201807072216~ubuntu18.04.1   amd64        ICE library (shared library)
ii  libwinpr-tools2-2:amd64                    2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Windows Portable Runtime Tools library
ii  libwinpr2-2:amd64                          2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Windows Portable Runtime library
ii  pidgin                                     1:2.12.0-1ubuntu4                          amd64        graphical multi-protocol instant messaging client
ii  pidgin-data                                1:2.12.0-1ubuntu4                          all          multi-protocol instant messaging client - data files
ii  pidgin-libnotify                           0.14-9ubuntu2                              amd64        display notification bubbles in pidgin
ii  pidgin-sipe                                1.23.2+sipe-0+201808031048~ubuntu18.04.1   amd64        Pidgin plugin for Skype for Business and Microsoft Lync
ii  remmina                                    1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        GTK+ Remote Desktop Client
ii  remmina-common                             1.2.0-rcgit.29+dfsg-1ubuntu1               all          Common files for Remmina
ii  remmina-plugin-rdp:amd64                   1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        RDP plugin for Remmina
ii  remmina-plugin-secret:amd64                1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        Secret plugin for Remmina
ii  remmina-plugin-vnc:amd64                   1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        VNC plugin for Remmina
```

**Comment by Daisuke-sama** [comment] 2018-08-10 08:25
I still have the same issue.
And I see you have 19 packages, I am 16
```
1:ii  freerdp2-x11                               2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        RDP client for Windows Terminal Services (X11 client)
2:ii  gstreamer1.0-nice:amd64                    0.1.15~sipe-0+201807072216~ubuntu18.04.1   amd64        ICE library (GStreamer plugin)
3:ii  libfarstream-0.2-5:amd64                   0.2.8-4.1~build1                           amd64        Audio/Video communications framework: core library
4:ii  libfreerdp-client2-2:amd64                 2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Free Remote Desktop Protocol library (client library)
5:ii  libfreerdp2-2:amd64                        2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Free Remote Desktop Protocol library (core library)
6:ii  libnice10:amd64                            0.1.15~sipe-0+201807072216~ubuntu18.04.1   amd64        ICE library (shared library)
7:ii  libwinpr2-2:amd64                          2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Windows Portable Runtime library
8:ii  pidgin                                     1:2.12.0-1ubuntu4                          amd64        graphical multi-protocol instant messaging client
9:ii  pidgin-data                                1:2.12.0-1ubuntu4                          all          multi-protocol instant messaging client - data files
10:ii  pidgin-libnotify                           0.14-9ubuntu2                              amd64        display notification bubbles in pidgin
11:ii  pidgin-sipe                                1.23.2-1                                   amd64        Pidgin plugin for Skype for Business and Microsoft Lync
12:ii  remmina                                    1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        GTK+ Remote Desktop Client
13:ii  remmina-common                             1.2.0-rcgit.29+dfsg-1ubuntu1               all          Common files for Remmina
14:ii  remmina-plugin-rdp:amd64                   1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        RDP plugin for Remmina
15:ii  remmina-plugin-secret:amd64                1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        Secret plugin for Remmina
16:ii  remmina-plugin-vnc:amd64                   1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        VNC plugin for Remmina
```
I'll try to completely remove applications and reinstall. I assume, there is something weird with my OS.

**Comment by xhaakon** [comment] 2018-08-10 20:53
You still have pidgin-sipe 1.23.2-1 from Ubuntu repo. You should install the 1.23.2+sipe-0+2018... version from the PPA...

**Comment by Daisuke-sama** [comment] 2018-08-12 10:24
I've completely purged packets and did the mandatory reboot. For removing I needed to use asterisk at the end of the remmina word, because it has a different names in its packages and doesn't want to be removed  in a simple way.

So, now I've reinstalled version of packages, and it seems I can present my desktop (not watching others'), but the app is crashing every few minutes after audio call or presentation.

Videocalling doesn't work. I think the issue relates to the driver.

**Comment by Daisuke-sama** [comment] 2018-08-14 13:17
Currently, I have the following packages installed. It seems that all works perfect.
```
ii  freerdp2-x11                               2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        RDP client for Windows Terminal Services (X11 client)
ii  gstreamer1.0-nice:amd64                    0.1.15~sipe-0+201807072216~ubuntu18.04.1   amd64        ICE library (GStreamer plugin)
ii  libfarstream-0.2-5:amd64                   0.2.8-4.1~build1                           amd64        Audio/Video communications framework: core library
ii  libfreerdp-client2-2:amd64                 2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-server2-2:amd64                 2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow-subsystem2-2:amd64       2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        FreeRDP Remote Desktop Protocol shadow subsystem libraries
ii  libfreerdp-shadow2-2:amd64                 2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp2-2:amd64                        2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Free Remote Desktop Protocol library (core library)
ii  libnice10:amd64                            0.1.15~sipe-0+201807072216~ubuntu18.04.1   amd64        ICE library (shared library)
ii  libwinpr-tools2-2:amd64                    2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Windows Portable Runtime Tools library
ii  libwinpr2-2:amd64                          2.0.0~git20180411.1.7a7b1802+dfsg1-2~sipe1 amd64        Windows Portable Runtime library
ii  pidgin                                     1:2.12.0-1ubuntu4                          amd64        graphical multi-protocol instant messaging client
ii  pidgin-data                                1:2.12.0-1ubuntu4                          all          multi-protocol instant messaging client - data files
ii  pidgin-libnotify                           0.14-9ubuntu2                              amd64        display notification bubbles in pidgin
ii  pidgin-sipe                                1.23.2+sipe-0+201808031048~ubuntu18.04.1   amd64        Pidgin plugin for Skype for Business and Microsoft Lync
ii  remmina                                    1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        GTK+ Remote Desktop Client
ii  remmina-common                             1.2.0-rcgit.29+dfsg-1ubuntu1               all          Common files for Remmina
ii  remmina-plugin-rdp:amd64                   1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        RDP plugin for Remmina
ii  remmina-plugin-secret:amd64                1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        Secret plugin for Remmina
ii  remmina-plugin-vnc:amd64                   1.2.0-rcgit.29+dfsg-1ubuntu1               amd64        VNC plugin for Remmina
```

**Comment by xhaakon** [comment] 2018-08-14 19:32
@Daisuke-sama That's great.

Also as I can't reproduce any issues with current Ubuntu 16.04 packages, which were the original topic of this ticket, I'm closing it.

**Closed as completed** 2018-08-14 19:35 UTC
