### ISSUE TITLE
"Share Whole Desktop" does not share all monitors.

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#66] opened 2016-05-10 11:21 UTC
...using this as a place holder for further investigation. 

This is a feature in a multi-monitor setup. I have a 6-screen setup in 3 columns x 2 rows. I did "Share Whole desktop", but it was only the upper 3:rd monitor that was shared.

**Comment by xhaakon** [comment] 2016-05-10 11:55
I can confirm this. From my two monitors only one (primary) is shared. Looks like a regression.

```
$ xrandr --listmonitors 
Monitors: 2
 0: +*HDMI1 1920/510x1080/287+0+0  HDMI1
 1: +eDP1 1920/293x1080/165+1920+0  eDP1
```

> only the upper 3:rd monitor that was shared.

@xnandersson Does that monitor have any special significance, i.e. what's your primary desktop? (Should be marked with an asterisk in the output of `xrandr --listmonitors`).

**Comment by xnandersson** [comment] 2016-05-10 12:51
Hrm...it looks like it might be that one.

Monitors: 6
 0: +*DisplayPort-0 1920/510x1080/290+3840+0  DisplayPort-0
 1: +DisplayPort-1 1920/510x1080/290+1920+0  DisplayPort-1
 2: +DisplayPort-2 1920/510x1080/290+0+1080  DisplayPort-2
 3: +DisplayPort-3 1920/510x1080/290+0+0  DisplayPort-3
 4: +DVI-0 1920/510x1080/290+3840+1080  DVI-0
 5: +DVI-1 1920/510x1080/290+1920+1080  DVI-1

**Comment by tmuehlhoff** [comment] 2016-05-11 06:48
Actually I think it's desireable to be able to chose only one screen to share.

**Comment by xhaakon** [comment] 2016-05-11 06:57
@tmuehlhoff Sipe lets you choose a screen to share if you have more than one. I haven't tested it for a while but it used to work.

**Comment by xhaakon** [comment] 2016-05-11 11:00
I've just tried sharing individual monitors and it works correctly.

This means only presenting all screens at once results in just the primary screen being shared.

**Comment by xnandersson** [comment] 2016-05-11 11:05
Yes, individual monitors works, but not "Share Whole Desktop". I guess in most cases you only want to share a specific screen, so the priority for this issue is not very high.

**Comment by xhaakon** [comment] 2016-05-12 11:04
The ability to share whole desktop was lost after a change in FreeRDP. I created a [PR](https://github.com/FreeRDP/FreeRDP/pull/3337) with them to re-introduce the feature.

My current fix at least seems to work as one would expect, but it likely isn't quite correct, which will be sorted out during the review.

You'll be soon able to test the new packages I'm building on launchpad :

```
freerdp2 - 2.0.0~git20160503.1.f828595+dfsg1-0~201605121049~ubuntu16.10.1
freerdp2 - 2.0.0~git20160503.1.f828595+dfsg1-0~201605121048~ubuntu16.04.1
freerdp2 - 2.0.0~git20160503.1.f828595+dfsg1-0~201605121048~ubuntu15.10.1
freerdp2 - 2.0.0~git20160503.1.f828595+dfsg1-0~201605121048~ubuntu15.04.1
freerdp2 - 2.0.0~git20160503.1.f828595+dfsg1-0~201605121048~ubuntu14.04.1
```

**Comment by xhaakon** [comment] 2016-05-26 08:37
Two weeks since the fix release have passed without any further problems reported. Considered as fixed and closing.

**Closed as completed by xhaakon** 2016-05-26 08:37 UTC
Labels: bug, fix ready for testing
