### ISSUE TITLE
libnice sometimes can't establish connection on multihomed hosts

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#86] opened 2016-05-26 10:03 UTC
On my computer I have this interface, setup by Virtualbox.

```
virbr0    Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          inet addr:192.168.122.1  Bcast:192.168.122.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

Having this interface blocks me from joining audio. I can see the shared screen though, and the chat.

If I disable the interface with:

>  sudo ip link set virbr0 down

...then I can connect just fine.

**Comment by xnandersson** [comment] 2016-05-27 10:27
I have a very strange observation. When I enabled exhaustive logging, I could connect to the audio even though virbr0 was present. I tried 3 times successfully. (I had GST_DEBUG=5 running)

Could this be some kind of race condition? That the i/o was slowing down the system enough for the setup of the call to be established?

**Comment by tmuehlhoff** [comment] 2016-05-27 12:21
I do have the same i/f, I can join audio, though I still have audio problems (even after the May 23rd patch), maybe related ?

**Comment by xhaakon** [comment] 2016-05-27 15:34
@tmuehlhoff If you can join audio, can you be more specific what your actual 'audio problems' are? Bad sound quality, you can hear the others speaking but they can't hear you, or something else?

**Comment by xhaakon** [comment] 2016-05-27 15:35
@tmuehlhoff Or maybe you're experiencing something like #85?

**Comment by xnandersson** [comment] 2016-05-30 10:38
Behaviour is strange. If I started pidgin normally (without logging), I could connect - no problem. The problem is there if I start Pidgin with logging. BUT if the logging is EXHAUSTIVE, I can AGAIN connect to audio. It is consistent, but strange consistent :-)

**Comment by xnandersson** [comment] 2016-05-30 16:47
I guess the title is not true, but I don't have a better name for it.... :-(

**Comment by xhaakon** [comment] 2016-06-01 11:49
@xnandersson Because the recent larger libnice update may have rendered this issue obsolete, I'm switching its state to 'more information needed'.

Please try to reproduce the bug with up-to-date PPA. Otherwise I'll close the ticket after 14 days, as is my common practice.

**Comment by xnandersson** [comment] 2016-06-01 11:51
@xhaakon Sure thing! I'll get at it :-)

**Comment by xhaakon** [comment] 2016-06-16 12:28
This issue hasn't been reproduced after a libnice update, so closing.

**Closed as completed by xhaakon** 2016-06-16 12:28 UTC
Labels: bug, more information needed
